language: java
jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
    - cd cob_spec 
script:
  - mvn package
  - java -jar fitnesse.jar -c "HttpTestSuite.ResponseTestSuite.SimpleGet?test"

